server:
  port: 8086
spring:
  application:
    name: user
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/user
    username: amigoscode
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
